
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 05 15:06:54 CET 2024
//----------------------------------------------------

package mini_python;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 29;
  public static final int MOD = 31;
  public static final int AND = 14;
  public static final int ELSE = 9;
  public static final int IDENT = 2;
  public static final int PLUS = 27;
  public static final int OR = 15;
  public static final int EQUAL = 22;
  public static final int LP = 17;
  public static final int IN = 13;
  public static final int RP = 18;
  public static final int NOT = 16;
  public static final int END = 25;
  public static final int RETURN = 10;
  public static final int DECINDENT = 6;
  public static final int IF = 8;
  public static final int COLON = 23;
  public static final int BEGIN = 24;
  public static final int COMMA = 21;
  public static final int CST = 3;
  public static final int LSQ = 19;
  public static final int EOF = 0;
  public static final int CMP = 4;
  public static final int DEF = 7;
  public static final int DIV = 30;
  public static final int MINUS = 28;
  public static final int NEWLINE = 26;
  public static final int INCINDENT = 5;
  public static final int PRINT = 11;
  public static final int error = 1;
  public static final int FOR = 12;
  public static final int RSQ = 20;
  public static final int UMINUS = 32;
}

